##
## Makefile for MiniLibX in /home/boulon/work/c/raytraceur/minilibx
## 
## Made by Olivier Crouzet
## Login   <ol@epitech.net>
## 
## Started on  Tue Oct  5 15:56:43 2004 Olivier Crouzet
## Last update Tue May 15 15:44:41 2007 Olivier Crouzet
##

## Please use configure script

#make MLX shut the fuck up
STFU = > /dev/null 2> /dev/null

all	: do_configure

do_configure	:
	./configure ${STFU}

clean	:
	./configure clean ${STFU}

fclean	: clean

re	: fclean clean all
